version: '3.8'

services:
  hadoop:
    container_name: hadoop
    build:
      context: ./hadoop/
      dockerfile: Dockerfile
    volumes:
      - ./wikipedia:/home/hduser/wikipedia
    ports:
      - 9864:9864
      - 9870:9870
      - 8088:8088
      - 9000:9000
      - 8020:8020