# Usa una imagen base de Python
FROM python:3.10.12

# Establece el directorio de trabajo
WORKDIR /database

# Copia el código fuente al contenedor
COPY . /database

# Instala las dependencias del proyecto
RUN pip install --upgrade pip